### ISSUE TITLE
Detect Pull Request Parameter in Action

### ISSUE THREAD

**Issue by rowi1de** [poad/github-pull-request-auto-merge-enable-action#621]
The GitHub Action context should contain all relevant data needed to identify in which pull request it is running. This would make Setup easier

**Comment by poad** [comment]
@rowi1de 
Thanks for your suggestion.

In what cases is this necessary?

This Action simply enables automatic merging of Pull Requests that match the Pull Request ID using the GraphQL API.
A Pull Request ID is all that is required.

Since it is a hassle to get the Pull Request ID on the Workflow side each time, we also provide a function to search for the Pull Request ID from the Pull Request Number.

**Comment by rowi1de** [comment]
Hey, my use case was to let the action run in a pr which should be merged.

I switched to an alternative now https://github.com/rowi1de/graphql-reactive/blob/main/.github/workflows/auto-merge-dependabot.yaml

**Comment by poad** [comment]
@rowi1de
dependabot [bot] can't run because it doesn't have permissions.

Do you want everyone to check the same condition in the action, because it is useless to put it in the if of the workflow?

**Comment by rowi1de** [comment]
@poad no seems like I misunderstood the purpose of this action 🙂
